### PR TITLE
Add Merge command

### LINKED ISSUE #25: [Feature Request] Merge from command line
I would like to be able to merge two or more files directly from the command line. 

What do you think about such a feature ? Would you merge a PR ?

### PR DESCRIPTION
**Pull request by erichard**
The command:
 1. read the input changelog from the config
 2. merge all files given to the command
 3. Ouput a merged changelog according to the config

Fix #25

### CODE REVIEW

**Comment by erichard** [comment]
Travis failure seems unrelated to the branch.

**Comment by emlynwest** [comment]
Thank you! I'll have a proper look later today/tomorrow, I've not been able to really do any OS work for a long time now and have been a bit out of things so I'll have to do some poking about to see why travis is failing.

**Comment by emlynwest** [comment]
I've had a look through, my only comments would be please make sure you're using tabs, not spaces, and can you update the readme to include the new command please?

As for the failing build that's no issue, I think I'm going to drop support for HHVM anyway.

**Comment by erichard** [comment]
@emlynwest I've made the changes

**Comment by emlynwest** [comment]
Thanks! I'll do some extra clean up today, seems there's a few housekeeping things that need to be done as well 😄

**Pull request merged**
